name: Deploy para Hostinger (Produção)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pegar o código fonte
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências e Gerar Site
        run: |
          npm install
          npx @11ty/eleventy

      - name: Publicar arquivos na branch deploy
        run: |
          cd _site
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "deploy: ${{ github.sha }}"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:deploy
